// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqgvnimksyefozzfapxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xZ3ZuaW1rc3llZm96emZhcHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzAxNjMsImV4cCI6MjA2NDAwNjE2M30.WYyQvE7y0yMjUNrY14qZafstpb6nJuyUhMgMWDD9i70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);